#!/usr/bin/env bash
# Transfers a file from our client to a server

# Check if all parameters were supplied
if [ "$#" -lt 4 ]; then
	echo "Usage $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assign parameters to variables
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# Construct scp command
SCP_COMMAND="scp -o StrictHostKeyChecking=no -i $PATH_TO_SSH_KEY $PATH_TO_FILE $USERNAME@$IP:~/"

# Execute scp command
$SCP_COMMAND
