#!/usr/bin/env bash
# SSH configuration
Host *
    PasswordAuthentication no
    GSSAPIDelegateCredentials no
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
